name = "tasun-api"
main = "worker.js"
compatibility_date = "2026-02-01"

[[d1_databases]]
binding = "DB"
database_name = "tasun_db"
database_id = "ecb1ff1d-eb3d-4fe8-ba2c-8b7cc884bd84"

[vars]
TEAM_DOMAIN = "https://<your-team-name>.cloudflareaccess.com"
POLICY_AUD = "<your-access-app-aud>"
ALLOWED_ORIGIN = "https://wutasun.github.io"

