name = "tasun-api"
main = "worker.js"
compatibility_date = "2026-02-01"

# 建議保留（預設通常是 true，但寫出來更穩）
workers_dev = true

# 建議開（壓縮後部署更快）
minify = true

[[d1_databases]]
binding = "DB"
database_name = "tasun-api"
database_id = "ecb1ff1d-eb3d-4fe8-ba2c-8b7cc884bd84"

[vars]
TEAM_DOMAIN = "https://tasun.cloudflareaccess.com"
POLICY_AUD = "62578ed4c22ba3d94bf6d6f9372069c9769bef9cd46596ec12c33666a077b98f"
ALLOWED_ORIGIN = "https://wutasun.github.io"

# ---- 如果你有自訂網域要綁 route（可選，沒用就留註解）----
# routes = [
#   { pattern = "api.yourdomain.com/*", zone_name = "yourdomain.com" }
# ]
