name = "tasun-api"
main = "worker.js"
compatibility_date = "2026-02-01"

[[d1_databases]]
binding = "DB"
database_name = "tasun-api"
database_id = "ecb1ff1d-eb3d-4fe8-ba2c-8b7cc884bd84"

[vars]
TEAM_DOMAIN = "https://tasun.cloudflareaccess.com"
POLICY_AUD = "62578ed4c22ba3d94bf6d6f9372069c9769bef9cd46596ec12c33666a077b98f"
ALLOWED_ORIGIN = "https://wutasun.github.io"
