name = "tasun-worker"
main = "worker_tasun.js"
compatibility_date = "2026-02-14"

# ⚠️ 請把下列 D1 binding 名稱與 database_id 改成你自己的
[[d1_databases]]
binding = "DB"
database_name = "tasun-db"
database_id = "ecb1ff1d-eb3d-4fe8-ba2c-8b7cc884bd84"

